<template>
  <div class="app-shell">
    <aside class="side-rail" :class="{open:mobileNav}">
      <router-link class="brand" to="/"><span class="brand-mark">EF</span><span><strong>智卷云</strong><small>高中教研工作台</small></span></router-link>
      <div class="workspace-switch">高中数学 <span>教师空间</span></div>
      <nav aria-label="主导航"><template v-for="group in navGroups" :key="group.label"><div class="nav-label">{{group.label}}</div><router-link v-for="item in group.items" :key="item.path" :to="item.path" :class="{active:isActive(item.path)}" :title="item.title" @click="mobileNav=false"><el-icon><component :is="item.icon"/></el-icon><span>{{item.title}}</span></router-link></template></nav>
      <div class="side-bottom"><span class="mode-dot"></span>本地演示工作区<small>高中与高考 · 内容待接入</small></div>
    </aside>
    <button v-if="mobileNav" class="nav-scrim" aria-label="关闭导航" @click="mobileNav=false"></button>
    <div class="main-shell"><header class="topbar"><div class="top-left"><el-button class="menu-toggle" :icon="Menu" circle aria-label="打开导航" @click="mobileNav=!mobileNav"/><div class="crumbs"><span>教师工作台</span><b>/</b><strong>{{pageTitle}}</strong></div></div><div class="top-actions"><el-button :icon="ShoppingCart" @click="basketOpen=true">试题篮 <b class="basket-count">{{basket.length}}</b></el-button><el-dropdown v-if="user" trigger="click"><button class="user-button"><el-icon><User/></el-icon>{{user.nickname || '我的账号'}}</button><template #dropdown><el-dropdown-menu><el-dropdown-item @click="$router.push('/me')">个人空间</el-dropdown-item><el-dropdown-item @click="logout">退出登录</el-dropdown-item></el-dropdown-menu></template></el-dropdown><el-button v-else :icon="User" text @click="$router.push('/login')">登录</el-button></div></header>
      <main class="content-area"><router-view/></main><footer class="foot">智卷云 · 前端演示环境 · 样例内容不代表真实考试资源</footer>
    </div>
    <el-drawer v-model="basketOpen" title="试题篮" size="min(440px, 100vw)"><div class="drawer-summary"><span><strong>{{basket.length}}</strong> / 100 道</span><el-button type="primary" :disabled="!basket.length" @click="$router.push('/papers');basketOpen=false">进入组卷</el-button></div><article v-for="item in basket" :key="item.id" class="basket-item"><div><el-tag size="small">{{item.type}}</el-tag><p>{{item.stem.replace(/\$/g,'').slice(0,85)}}</p></div><el-button :icon="Delete" circle text :aria-label="'移除题目 '+item.id" @click="removeQuestion(item.id)"/></article><el-empty v-if="!basket.length" description="暂无试题"/></el-drawer>
  </div>
</template>
<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { House, Search, Document, DocumentChecked, Files, CircleCheck, Collection, Notebook, MagicStick, CreditCard, EditPen, User, ShoppingCart, Delete, Menu, Coin } from '@element-plus/icons-vue'
import http from './api/request'
import { useWorkspace } from './composables/workspace'
const route=useRoute(), user=ref(null), basketOpen=ref(false), mobileNav=ref(false)
const {basket,removeQuestion}=useWorkspace()
const navGroups=[{label:'选题与组卷',items:[{path:'/',title:'工作台',icon:House},{path:'/questions',title:'题库选题',icon:Search},{path:'/paper-library',title:'试卷选题',icon:Files},{path:'/papers',title:'组卷工作台',icon:Document},{path:'/assignments',title:'作业管理',icon:DocumentChecked},{path:'/practice',title:'练习与错题',icon:CircleCheck}]},{label:'教学与服务',items:[{path:'/resources',title:'教学资源',icon:Collection},{path:'/my-assignments',title:'我的作业',icon:Notebook},{path:'/figures',title:'数学图形',icon:EditPen},{path:'/aisearch',title:'AI 教研助手',icon:MagicStick},{path:'/vip',title:'会员与点数',icon:CreditCard},{path:'/creator',title:'创作者中心',icon:Coin},{path:'/me',title:'个人空间',icon:User}]}]
const pageTitle=computed(()=>navGroups.flatMap(g=>g.items).find(item=>item.path===route.path)?.title||(route.path==='/login'?'账号登录':'题目详情'))
function isActive(path){return path==='/'?route.path==='/':route.path===path||(path==='/questions'&&route.path.startsWith('/questions/'))}
async function syncUser(){if(!localStorage.getItem('examforge_token')){user.value=null;return}try{user.value=await http.get('/auth/me')}catch{user.value=null}}
onMounted(syncUser)
watch(()=>route.path,(path,previous)=>{mobileNav.value=false;if(previous==='/login')syncUser()})
function logout(){localStorage.removeItem('examforge_token');user.value=null}
</script>
<style>
@import './styles/global.css';
.app-shell{display:grid;grid-template-columns:220px minmax(0,1fr);min-height:100vh}.side-rail{position:sticky;top:0;height:100vh;background:#17222d;color:#c2cbd2;padding:24px 14px;display:flex;flex-direction:column;z-index:30}.brand{display:flex;gap:11px;align-items:center;text-decoration:none;color:white;padding:0 10px 25px}.brand-mark{background:#23847e;display:grid;place-items:center;width:35px;height:35px;border-radius:7px;font-size:13px;font-weight:700}.brand strong{font-size:19px}.brand small{display:block;margin-top:4px;font-size:11px;color:#99aab6}.workspace-switch{border-top:1px solid #36424c;border-bottom:1px solid #36424c;padding:15px 10px;font-size:12px}.workspace-switch span{float:right;color:#91a4b2}.nav-label{font-size:11px;color:#8b9da9;margin:23px 12px 9px}.side-rail nav{overflow-y:auto}.side-rail nav a{display:flex;gap:12px;align-items:center;min-height:42px;padding:10px 13px;margin:3px 0;text-decoration:none;color:#b9c5cf;border-radius:5px;font-size:13px}.side-rail nav a:hover{background:#24343e}.side-rail nav a.active{background:#254441;color:#e2fff4}.side-rail nav .el-icon{font-size:18px;flex:none}.side-bottom{margin-top:auto;padding:20px 12px 0;font-size:11px;color:#b8c4cd}.side-bottom small{display:block;font-size:10px;color:#8596a3;margin:8px 0 0 12px}.mode-dot{display:inline-block;background:#44bc91;width:6px;height:6px;border-radius:50%;margin-right:7px}.main-shell{min-width:0;display:flex;flex-direction:column}.topbar{height:68px;flex:none;background:#fff;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 30px;gap:12px}.top-left,.top-actions{display:flex;align-items:center;gap:10px;min-width:0}.crumbs{font-size:12px;white-space:nowrap}.crumbs span{color:#8997a5}.crumbs b{font-weight:400;margin:0 10px;color:#bac3cb}.crumbs strong{font-weight:500}.basket-count{color:#187d6e;margin-left:8px}.user-button{border:0;background:none;display:flex;align-items:center;gap:6px;color:#526376;cursor:pointer}.content-area{padding:28px 30px;flex:1;min-width:0;max-width:1600px;width:100%;margin:auto}.foot{font-size:11px;color:#7f8c98;text-align:center;padding:20px 12px}.menu-toggle{display:none!important}.nav-scrim{display:none}.drawer-summary{display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line);padding-bottom:20px}.drawer-summary strong{font-size:24px;margin-right:5px}.basket-item{display:flex;gap:10px;align-items:center;border-bottom:1px solid var(--line);padding:15px 0}.basket-item>div{min-width:0;flex:1}.basket-item p{font-size:12px;line-height:1.8;color:var(--text-2);overflow-wrap:anywhere;margin-bottom:0}
@media(max-width:1100px) and (min-width:701px){.app-shell{grid-template-columns:72px minmax(0,1fr)}.side-rail{padding:20px 9px}.brand{padding:0 9px 15px}.brand>span:last-child,.workspace-switch,.nav-label,.side-bottom,.side-rail nav a>span:not(.el-icon){display:none}.side-rail nav a{justify-content:center;padding:12px}.side-rail nav{margin-top:10px}.content-area{padding:22px}.topbar{padding:0 22px}}
@media(max-width:700px){.app-shell{display:block}.side-rail{position:fixed;left:0;top:0;width:240px;transform:translateX(-100%);transition:transform .18s}.side-rail.open{transform:translateX(0)}.nav-scrim{display:block;position:fixed;inset:0;background:#0006;border:0;z-index:25}.menu-toggle{display:inline-flex!important}.topbar{padding:0 12px;height:60px}.crumbs span,.crumbs b{display:none}.top-actions{gap:2px}.top-actions>.el-button{padding:8px}.content-area{padding:20px 14px}.foot{line-height:1.8}.topbar .el-button+.el-button{margin-left:0}}
@media print{.side-rail,.topbar,.foot,.nav-scrim,.el-overlay{display:none!important}.app-shell,.main-shell{display:block!important}.content-area{padding:0!important;max-width:none}.app-shell{background:white}body{background:#fff!important}}
</style>
