<template>
  <div class="editor-page">
    <header class="page-head"><div><h1 class="page-title">数学图形工作台</h1><p class="page-subtitle">绘制可编辑几何图形，导出矢量 SVG；图片导入仅供本机预览</p></div><div class="head-actions"><el-button @click="undo" :disabled="!shapes.length" title="撤销上一步">↶</el-button><el-button @click="clear" :disabled="!shapes.length">清空</el-button><el-button type="primary" @click="downloadSvg">导出 SVG</el-button></div></header>
    <div class="editor-layout"><aside class="tools-panel"><h2>绘图工具</h2><div class="tool-grid"><button v-for="item in tools" :key="item.id" :class="{active:tool===item.id}" @click="tool=item.id;pending=null" :title="item.help">{{item.label}}</button></div><label>颜色 <input v-model="color" type="color"></label><label>线宽 <el-input-number v-model="strokeWidth" :min="1" :max="8" size="small"/></label><label>标注文字 <el-input v-model="label" maxlength="12" placeholder="如 A、O、x"/></label><label>背景参考图 <input type="file" accept="image/png,image/jpeg,image/webp" @change="loadImage"></label><el-button v-if="background" size="small" @click="background=''">移除参考图</el-button><p class="note">参考图不会写入 SVG。题目入库前需由服务端完成图片格式检查、病毒扫描和尺寸限制。</p></aside>
      <main class="canvas-panel"><div class="canvas-head"><strong>几何画布</strong><span>{{shapes.length}} 个图元 · {{pending?'再选择一个位置完成图形':'点击画布开始绘制'}}</span></div><svg ref="canvas" viewBox="0 0 800 500" role="img" aria-label="数学图形编辑画布" @click="draw"><defs><pattern id="grid" width="25" height="25" patternUnits="userSpaceOnUse"><path d="M 25 0 L 0 0 0 25" fill="none" stroke="#edf1f5" stroke-width="1"/></pattern></defs><rect width="800" height="500" fill="white"/><image v-if="background" :href="background" x="0" y="0" width="800" height="500" preserveAspectRatio="xMidYMid meet" opacity=".35"/><rect width="800" height="500" fill="url(#grid)"/><template v-for="(shape,i) in shapes" :key="i"><circle v-if="shape.kind==='point'" :cx="shape.x" :cy="shape.y" r="4" :fill="shape.color"/><line v-else-if="shape.kind==='line'" :x1="shape.x" :y1="shape.y" :x2="shape.x2" :y2="shape.y2" :stroke="shape.color" :stroke-width="shape.width"/><circle v-else-if="shape.kind==='circle'" :cx="shape.x" :cy="shape.y" :r="shape.radius" fill="none" :stroke="shape.color" :stroke-width="shape.width"/><text v-else :x="shape.x" :y="shape.y" :fill="shape.color" font-size="20">{{shape.text}}</text></template><circle v-if="pending" :cx="pending.x" :cy="pending.y" r="5" fill="#3278d8"/></svg><div class="canvas-foot"><span>800 × 500 · SVG 矢量画布</span><span>本地草稿自动保存</span></div></main></div>
  </div>
</template>
<script setup>
import { onMounted, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
const tools=[{id:'point',label:'点',help:'放置点'},{id:'line',label:'线段',help:'依次点击两个端点'},{id:'circle',label:'圆',help:'依次点击圆心和半径点'},{id:'text',label:'标注',help:'点击位置放置文字'}]
const tool=ref('point'),color=ref('#286ea9'),strokeWidth=ref(2),label=ref('A'),shapes=ref([]),pending=ref(null),background=ref(''),canvas=ref(null)
onMounted(()=>{try{shapes.value=JSON.parse(localStorage.getItem('examforge_figure_draft')||'[]')}catch{shapes.value=[]}})
watch(shapes,value=>localStorage.setItem('examforge_figure_draft',JSON.stringify(value)),{deep:true})
function draw(event){const point=canvas.value.createSVGPoint();point.x=event.clientX;point.y=event.clientY;const p=point.matrixTransform(canvas.value.getScreenCTM().inverse());const x=Math.round(Math.max(0,Math.min(800,p.x))),y=Math.round(Math.max(0,Math.min(500,p.y)));if(tool.value==='point'){shapes.value.push({kind:'point',x,y,color:color.value});return}if(tool.value==='text'){if(!label.value.trim()){ElMessage.warning('请先输入标注文字');return}shapes.value.push({kind:'text',x,y,text:label.value.trim(),color:color.value});return}if(!pending.value){pending.value={x,y};return}const first=pending.value;shapes.value.push(tool.value==='line'?{kind:'line',x:first.x,y:first.y,x2:x,y2:y,color:color.value,width:strokeWidth.value}:{kind:'circle',x:first.x,y:first.y,radius:Math.round(Math.hypot(x-first.x,y-first.y)),color:color.value,width:strokeWidth.value});pending.value=null}
function undo(){if(pending.value){pending.value=null;return}shapes.value.pop()}
function clear(){shapes.value=[];pending.value=null}
function escapeXml(value){return String(value).replace(/[<>&"']/g,char=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[char]))}
function downloadSvg(){if(!shapes.value.length){ElMessage.warning('请先绘制图形');return}const body=shapes.value.map(s=>s.kind==='point'?'<circle cx="'+s.x+'" cy="'+s.y+'" r="4" fill="'+s.color+'"/>':s.kind==='line'?'<line x1="'+s.x+'" y1="'+s.y+'" x2="'+s.x2+'" y2="'+s.y2+'" stroke="'+s.color+'" stroke-width="'+s.width+'"/>':s.kind==='circle'?'<circle cx="'+s.x+'" cy="'+s.y+'" r="'+s.radius+'" fill="none" stroke="'+s.color+'" stroke-width="'+s.width+'"/>':'<text x="'+s.x+'" y="'+s.y+'" fill="'+s.color+'" font-size="20">'+escapeXml(s.text)+'</text>').join('');const xml='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 500">'+body+'</svg>';const url=URL.createObjectURL(new Blob([xml],{type:'image/svg+xml'}));const a=document.createElement('a');a.href=url;a.download='math-figure.svg';a.click();URL.revokeObjectURL(url)}
function loadImage(event){const file=event.target.files?.[0];if(!file)return;if(file.size>5*1024*1024){ElMessage.warning('参考图不得超过 5 MB');return}const reader=new FileReader();reader.onload=()=>{background.value=reader.result};reader.readAsDataURL(file)}
</script>
<style scoped>
.editor-page{max-width:1400px;margin:auto}.page-head{display:flex;justify-content:space-between;gap:15px;align-items:center;margin-bottom:22px}.head-actions{display:flex;gap:8px}.editor-layout{display:grid;grid-template-columns:225px minmax(0,1fr);gap:18px}.tools-panel,.canvas-panel{background:white;border:1px solid var(--line);border-radius:8px;padding:18px}.tools-panel h2{font-size:14px;margin:0 0 15px}.tool-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.tool-grid button{border:1px solid var(--line);border-radius:5px;background:white;padding:10px;cursor:pointer}.tool-grid button.active{border-color:var(--primary);background:#edf5ff;color:var(--primary)}.tools-panel>label{display:block;margin-top:18px;font-size:12px;color:#607185}.tools-panel>label>*{display:block;margin-top:8px}.tools-panel input[type=file]{max-width:100%;font-size:11px}.note{font-size:11px;line-height:1.7;color:#8b99a7}.canvas-head,.canvas-foot{display:flex;justify-content:space-between;gap:10px;color:#8b9aaa;font-size:11px}.canvas-head strong{color:#32465c;font-size:14px}.canvas-panel svg{display:block;width:100%;aspect-ratio:8/5;border:1px solid var(--line);margin:14px 0;cursor:crosshair}.canvas-foot{color:#9aa8b6}@media(max-width:850px){.editor-layout{grid-template-columns:1fr}.page-head{align-items:flex-start;flex-direction:column}}
</style>
